In [1]:
import numpy as np

# numpy arry

In [2]:
myList = [10, 20, 30, 40, 50]

In [3]:
type(myList)

list

In [4]:
np.array(myList)

array([10, 20, 30, 40, 50])

In [9]:
matrixList = [[10, 20, 30], [30, 40, 50], [50, 60, 70]]

In [10]:
matrixList[1]

[30, 40, 50]

In [11]:
np.array(matrixList)

array([[10, 20, 30],
       [30, 40, 50],
       [50, 60, 70]])

# arange


In [12]:
list(range(0, 5))

[0, 1, 2, 3, 4]

In [13]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [14]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

# zeros

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# linspace

In [19]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

# eye

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# random

In [21]:
np.random.rand(5)

array([0.23429935, 0.38490016, 0.60012247, 0.53826146, 0.52784837])

In [22]:
np.random.rand(5, 5)

array([[0.64746528, 0.4980704 , 0.37064481, 0.99781295, 0.14165393],
       [0.33277233, 0.54219585, 0.07354635, 0.76833359, 0.45876002],
       [0.89187943, 0.7642017 , 0.85569339, 0.64753803, 0.82558708],
       [0.58669212, 0.17587616, 0.94978049, 0.85857703, 0.24370638],
       [0.11549243, 0.45245029, 0.65698428, 0.05043422, 0.33577621]])

In [23]:
np.random.randint(1, 100)

44

In [24]:
np.random.randint(1, 100, 10)

array([48, 21, 60,  5, 30, 72, 16, 48, 50, 60])

In [25]:
myNumpyArray = np.arange(25)

In [26]:
myNumpyArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
myNumpyArray = np.random.randint(0, 50, 10)

In [28]:
myNumpyArray

array([44, 39, 24, 41, 19,  6, 23,  7, 26, 32])

# numpy array methods

In [29]:
myNumpyArray.reshape(2, 5)

array([[44, 39, 24, 41, 19],
       [ 6, 23,  7, 26, 32]])

In [30]:
myNumpyArray.max()

44

In [31]:
myNumpyArray.min()

6

In [32]:
myNumpyArray.argmax()

0

In [33]:
myNumpyArray.argmin()

5

In [34]:
myNumpyArray.shape

(10,)

In [35]:
reshapedArray = myNumpyArray.reshape(2, 5)

In [36]:
reshapedArray.shape

(2, 5)