In [1]:
import numpy as np

In [5]:
myArry = np.arange(1,15)

In [6]:
myArry

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
 myArry[3]

4

In [8]:
myArry[3:8]

array([4, 5, 6, 7, 8])

In [9]:
myArry[3:8] = -5

In [10]:
myArry

array([ 1,  2,  3, -5, -5, -5, -5, -5,  9, 10, 11, 12, 13, 14])

In [13]:
myArry2 = np.arange(0, 24)
myArry2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [16]:
slicingArry = myArry2[4:9]
slicingArry

array([4, 5, 6, 7, 8])

In [17]:
slicingArry[:] = 100
slicingArry

array([100, 100, 100, 100, 100])

In [18]:
sampleArry = np.arange(0, 24)

In [19]:
sampleArry

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
sampleArryCopy = sampleArry.copy()

In [21]:
sampleArryCopySlice = sampleArryCopy[4:9]

In [22]:
sampleArryCopySlice[:] = 100
sampleArryCopySlice

array([100, 100, 100, 100, 100])

# matrix

In [23]:
myList = [[10,20,30],[40,50,60],[70,80,90]]

In [24]:
myMatrixArry = np.array(myList)

In [25]:
myMatrixArry

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [26]:
myMatrixArry[0]

array([10, 20, 30])

In [27]:
myMatrixArry[0][0]

10

In [28]:
myMatrixArry[0,0]

10

In [30]:
myMatrixArry[0:,2]

array([30, 60, 90])

# operations

In [31]:
newArry = np.arange(1,11)